version: '3'
services:
    app:
        build: .
        volumes:
            - .:/project
        ports:
            - "5000:5000"
    db:
        image: mysql:8.0
        ports:
            - "32000:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
        volumes:
            - ./db:/docker-entrypoint-initdb.d/:ro
