version: '3'
services:
    app:
        build: .
        volumes:
            - .:/project
        ports:
            - "5000:5000"
    db:
        image: mysql:5.7
        restart: always
        ports:
            - "32000:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_USER: 'root'
            MYSQL_PASS: 'root'
        volumes:
            - ./db:/var/lib/mysql
